namespace YifyCommon.Models.Constants
{
    public enum MovieGenre
    {
        Action,
        Adventure,
        Animation,
        Biography,
        Comedy,
        Crime,
        Documentary,
        Drama,
        Family,
        Fantasy,
        File_Noir,
        History,
        Horror,
        Music,
        Musical,
        Mystery,
        Romance,
        Sci_Fi,
        Short,
        Sport,
        Thriller,
        War,
        Western,
        All
    }
}
